[project]
name = "ragent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bm25s>=0.2.13",
    "openai>=1.99.6",
    "skypilot>=0.10.1",
    "verifiers>=0.1.2.post0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "ipywidgets>=8.1.7",
]
